services:
  web-os-process:
    image: web-os-process:latest
    container_name: web-os-process
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /proc:/proc
      - /:/host
    environment:
      - SI_ROOT_PATH=/host
